name: Build mod

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 7.4

      - name: Generate missing gradle-wrapper.jar
        run: gradle wrapper --gradle-version 7.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: afonesiboost-jar
          path: build/libs/*.jar
